#Server configurations
server:
  host: "localhost"
  port: "8000"

#Database configurations
database:
  uri: "mongodb://%s:%s@ds111895.mlab.com:11895/wcm_alpha?retryWrites=false"
  user: "trajectUser"
  pass: "Welcome123"

